// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: bookings.sql

package db

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const checkSlotConflict = `-- name: CheckSlotConflict :one
SELECT COUNT(*) FROM bookings
WHERE mentor_id = $1 AND session_date = $2 AND start_time = $3
AND status NOT IN ('cancelled_by_student', 'cancelled_by_mentor')
`

type CheckSlotConflictParams struct {
	MentorID    uuid.UUID   `json:"mentor_id"`
	SessionDate pgtype.Date `json:"session_date"`
	StartTime   pgtype.Time `json:"start_time"`
}

func (q *Queries) CheckSlotConflict(ctx context.Context, arg CheckSlotConflictParams) (int64, error) {
	row := q.db.QueryRow(ctx, checkSlotConflict, arg.MentorID, arg.SessionDate, arg.StartTime)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countAllBookings = `-- name: CountAllBookings :one
SELECT COUNT(*) FROM bookings
`

func (q *Queries) CountAllBookings(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countAllBookings)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countBookingsByStatus = `-- name: CountBookingsByStatus :one
SELECT COUNT(*) FROM bookings WHERE status = $1
`

func (q *Queries) CountBookingsByStatus(ctx context.Context, status string) (int64, error) {
	row := q.db.QueryRow(ctx, countBookingsByStatus, status)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countMentorBookings = `-- name: CountMentorBookings :one
SELECT COUNT(*) FROM bookings WHERE mentor_id = $1
`

func (q *Queries) CountMentorBookings(ctx context.Context, mentorID uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countMentorBookings, mentorID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countStudentBookings = `-- name: CountStudentBookings :one
SELECT COUNT(*) FROM bookings WHERE student_id = $1
`

func (q *Queries) CountStudentBookings(ctx context.Context, studentID uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countStudentBookings, studentID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createBooking = `-- name: CreateBooking :one
INSERT INTO bookings (
    student_id, mentor_id, plan_id, session_date, start_time, end_time, google_meet_link, status, coupon_id
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, 'confirmed', $8
)
RETURNING id, student_id, mentor_id, plan_id, session_date, start_time, end_time, google_meet_link, status, created_at, updated_at, coupon_id
`

type CreateBookingParams struct {
	StudentID      uuid.UUID   `json:"student_id"`
	MentorID       uuid.UUID   `json:"mentor_id"`
	PlanID         uuid.UUID   `json:"plan_id"`
	SessionDate    pgtype.Date `json:"session_date"`
	StartTime      pgtype.Time `json:"start_time"`
	EndTime        pgtype.Time `json:"end_time"`
	GoogleMeetLink *string     `json:"google_meet_link"`
	CouponID       pgtype.UUID `json:"coupon_id"`
}

func (q *Queries) CreateBooking(ctx context.Context, arg CreateBookingParams) (Booking, error) {
	row := q.db.QueryRow(ctx, createBooking,
		arg.StudentID,
		arg.MentorID,
		arg.PlanID,
		arg.SessionDate,
		arg.StartTime,
		arg.EndTime,
		arg.GoogleMeetLink,
		arg.CouponID,
	)
	var i Booking
	err := row.Scan(
		&i.ID,
		&i.StudentID,
		&i.MentorID,
		&i.PlanID,
		&i.SessionDate,
		&i.StartTime,
		&i.EndTime,
		&i.GoogleMeetLink,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CouponID,
	)
	return i, err
}

const getBookingByID = `-- name: GetBookingByID :one
SELECT id, student_id, mentor_id, plan_id, session_date, start_time, end_time, google_meet_link, status, created_at, updated_at, coupon_id FROM bookings WHERE id = $1
`

func (q *Queries) GetBookingByID(ctx context.Context, id uuid.UUID) (Booking, error) {
	row := q.db.QueryRow(ctx, getBookingByID, id)
	var i Booking
	err := row.Scan(
		&i.ID,
		&i.StudentID,
		&i.MentorID,
		&i.PlanID,
		&i.SessionDate,
		&i.StartTime,
		&i.EndTime,
		&i.GoogleMeetLink,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CouponID,
	)
	return i, err
}

const getBookingsByMentorAndDate = `-- name: GetBookingsByMentorAndDate :many
SELECT id, student_id, mentor_id, plan_id, session_date, start_time, end_time, google_meet_link, status, created_at, updated_at, coupon_id FROM bookings 
WHERE mentor_id = $1 AND session_date = $2 
AND status NOT IN ('cancelled_by_student', 'cancelled_by_mentor')
`

type GetBookingsByMentorAndDateParams struct {
	MentorID    uuid.UUID   `json:"mentor_id"`
	SessionDate pgtype.Date `json:"session_date"`
}

func (q *Queries) GetBookingsByMentorAndDate(ctx context.Context, arg GetBookingsByMentorAndDateParams) ([]Booking, error) {
	rows, err := q.db.Query(ctx, getBookingsByMentorAndDate, arg.MentorID, arg.SessionDate)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Booking{}
	for rows.Next() {
		var i Booking
		if err := rows.Scan(
			&i.ID,
			&i.StudentID,
			&i.MentorID,
			&i.PlanID,
			&i.SessionDate,
			&i.StartTime,
			&i.EndTime,
			&i.GoogleMeetLink,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.CouponID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAllBookings = `-- name: ListAllBookings :many
SELECT 
    b.id, b.student_id, b.mentor_id, b.plan_id, b.session_date, b.start_time, b.end_time, b.google_meet_link, b.status, b.created_at, b.updated_at, b.coupon_id,
    mp.title AS plan_title,
    su.name AS student_name,
    mu.name AS mentor_name
FROM bookings b
JOIN mentorship_plans mp ON mp.id = b.plan_id
JOIN users su ON su.id = b.student_id
JOIN users mu ON mu.id = b.mentor_id
ORDER BY b.created_at DESC 
LIMIT $1 OFFSET $2
`

type ListAllBookingsParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

type ListAllBookingsRow struct {
	ID             uuid.UUID   `json:"id"`
	StudentID      uuid.UUID   `json:"student_id"`
	MentorID       uuid.UUID   `json:"mentor_id"`
	PlanID         uuid.UUID   `json:"plan_id"`
	SessionDate    pgtype.Date `json:"session_date"`
	StartTime      pgtype.Time `json:"start_time"`
	EndTime        pgtype.Time `json:"end_time"`
	GoogleMeetLink *string     `json:"google_meet_link"`
	Status         string      `json:"status"`
	CreatedAt      time.Time   `json:"created_at"`
	UpdatedAt      time.Time   `json:"updated_at"`
	CouponID       pgtype.UUID `json:"coupon_id"`
	PlanTitle      string      `json:"plan_title"`
	StudentName    string      `json:"student_name"`
	MentorName     string      `json:"mentor_name"`
}

func (q *Queries) ListAllBookings(ctx context.Context, arg ListAllBookingsParams) ([]ListAllBookingsRow, error) {
	rows, err := q.db.Query(ctx, listAllBookings, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListAllBookingsRow{}
	for rows.Next() {
		var i ListAllBookingsRow
		if err := rows.Scan(
			&i.ID,
			&i.StudentID,
			&i.MentorID,
			&i.PlanID,
			&i.SessionDate,
			&i.StartTime,
			&i.EndTime,
			&i.GoogleMeetLink,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.CouponID,
			&i.PlanTitle,
			&i.StudentName,
			&i.MentorName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMentorBookings = `-- name: ListMentorBookings :many
SELECT
    b.id, b.student_id, b.mentor_id, b.plan_id, b.session_date, b.start_time, b.end_time, b.google_meet_link, b.status, b.created_at, b.updated_at, b.coupon_id,
    mp.title AS plan_title,
    u.name AS student_name
FROM bookings b
JOIN mentorship_plans mp ON mp.id = b.plan_id
JOIN users u ON u.id = b.student_id
WHERE b.mentor_id = $1
ORDER BY b.session_date DESC, b.start_time DESC
LIMIT $2 OFFSET $3
`

type ListMentorBookingsParams struct {
	MentorID uuid.UUID `json:"mentor_id"`
	Limit    int32     `json:"limit"`
	Offset   int32     `json:"offset"`
}

type ListMentorBookingsRow struct {
	ID             uuid.UUID   `json:"id"`
	StudentID      uuid.UUID   `json:"student_id"`
	MentorID       uuid.UUID   `json:"mentor_id"`
	PlanID         uuid.UUID   `json:"plan_id"`
	SessionDate    pgtype.Date `json:"session_date"`
	StartTime      pgtype.Time `json:"start_time"`
	EndTime        pgtype.Time `json:"end_time"`
	GoogleMeetLink *string     `json:"google_meet_link"`
	Status         string      `json:"status"`
	CreatedAt      time.Time   `json:"created_at"`
	UpdatedAt      time.Time   `json:"updated_at"`
	CouponID       pgtype.UUID `json:"coupon_id"`
	PlanTitle      string      `json:"plan_title"`
	StudentName    string      `json:"student_name"`
}

func (q *Queries) ListMentorBookings(ctx context.Context, arg ListMentorBookingsParams) ([]ListMentorBookingsRow, error) {
	rows, err := q.db.Query(ctx, listMentorBookings, arg.MentorID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListMentorBookingsRow{}
	for rows.Next() {
		var i ListMentorBookingsRow
		if err := rows.Scan(
			&i.ID,
			&i.StudentID,
			&i.MentorID,
			&i.PlanID,
			&i.SessionDate,
			&i.StartTime,
			&i.EndTime,
			&i.GoogleMeetLink,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.CouponID,
			&i.PlanTitle,
			&i.StudentName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listStudentBookings = `-- name: ListStudentBookings :many
SELECT
    b.id, b.student_id, b.mentor_id, b.plan_id, b.session_date, b.start_time, b.end_time, b.google_meet_link, b.status, b.created_at, b.updated_at, b.coupon_id,
    mp.title AS plan_title,
    u.name AS mentor_name
FROM bookings b
JOIN mentorship_plans mp ON mp.id = b.plan_id
JOIN users u ON u.id = b.mentor_id
WHERE b.student_id = $1
ORDER BY b.session_date DESC, b.start_time DESC
LIMIT $2 OFFSET $3
`

type ListStudentBookingsParams struct {
	StudentID uuid.UUID `json:"student_id"`
	Limit     int32     `json:"limit"`
	Offset    int32     `json:"offset"`
}

type ListStudentBookingsRow struct {
	ID             uuid.UUID   `json:"id"`
	StudentID      uuid.UUID   `json:"student_id"`
	MentorID       uuid.UUID   `json:"mentor_id"`
	PlanID         uuid.UUID   `json:"plan_id"`
	SessionDate    pgtype.Date `json:"session_date"`
	StartTime      pgtype.Time `json:"start_time"`
	EndTime        pgtype.Time `json:"end_time"`
	GoogleMeetLink *string     `json:"google_meet_link"`
	Status         string      `json:"status"`
	CreatedAt      time.Time   `json:"created_at"`
	UpdatedAt      time.Time   `json:"updated_at"`
	CouponID       pgtype.UUID `json:"coupon_id"`
	PlanTitle      string      `json:"plan_title"`
	MentorName     string      `json:"mentor_name"`
}

func (q *Queries) ListStudentBookings(ctx context.Context, arg ListStudentBookingsParams) ([]ListStudentBookingsRow, error) {
	rows, err := q.db.Query(ctx, listStudentBookings, arg.StudentID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListStudentBookingsRow{}
	for rows.Next() {
		var i ListStudentBookingsRow
		if err := rows.Scan(
			&i.ID,
			&i.StudentID,
			&i.MentorID,
			&i.PlanID,
			&i.SessionDate,
			&i.StartTime,
			&i.EndTime,
			&i.GoogleMeetLink,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.CouponID,
			&i.PlanTitle,
			&i.MentorName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateBookingStatus = `-- name: UpdateBookingStatus :exec
UPDATE bookings SET status = $2, updated_at = NOW() WHERE id = $1
`

type UpdateBookingStatusParams struct {
	ID     uuid.UUID `json:"id"`
	Status string    `json:"status"`
}

func (q *Queries) UpdateBookingStatus(ctx context.Context, arg UpdateBookingStatusParams) error {
	_, err := q.db.Exec(ctx, updateBookingStatus, arg.ID, arg.Status)
	return err
}
