// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: coupons.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createCoupon = `-- name: CreateCoupon :one
INSERT INTO coupons (
    code, student_id, discount_percentage, expires_at
) VALUES (
    $1, $2, $3, $4
)
RETURNING id, code, student_id, discount_percentage, is_used, expires_at, created_at
`

type CreateCouponParams struct {
	Code               string             `json:"code"`
	StudentID          uuid.UUID          `json:"student_id"`
	DiscountPercentage int32              `json:"discount_percentage"`
	ExpiresAt          pgtype.Timestamptz `json:"expires_at"`
}

func (q *Queries) CreateCoupon(ctx context.Context, arg CreateCouponParams) (Coupon, error) {
	row := q.db.QueryRow(ctx, createCoupon,
		arg.Code,
		arg.StudentID,
		arg.DiscountPercentage,
		arg.ExpiresAt,
	)
	var i Coupon
	err := row.Scan(
		&i.ID,
		&i.Code,
		&i.StudentID,
		&i.DiscountPercentage,
		&i.IsUsed,
		&i.ExpiresAt,
		&i.CreatedAt,
	)
	return i, err
}

const getValidCoupon = `-- name: GetValidCoupon :one
SELECT id, code, student_id, discount_percentage, is_used, expires_at, created_at FROM coupons
WHERE code = $1
  AND student_id = $2
  AND is_used = false
  AND (expires_at IS NULL OR expires_at > NOW())
LIMIT 1
`

type GetValidCouponParams struct {
	Code      string    `json:"code"`
	StudentID uuid.UUID `json:"student_id"`
}

func (q *Queries) GetValidCoupon(ctx context.Context, arg GetValidCouponParams) (Coupon, error) {
	row := q.db.QueryRow(ctx, getValidCoupon, arg.Code, arg.StudentID)
	var i Coupon
	err := row.Scan(
		&i.ID,
		&i.Code,
		&i.StudentID,
		&i.DiscountPercentage,
		&i.IsUsed,
		&i.ExpiresAt,
		&i.CreatedAt,
	)
	return i, err
}

const markCouponUnused = `-- name: MarkCouponUnused :exec
UPDATE coupons
SET is_used = false
WHERE id = $1
`

func (q *Queries) MarkCouponUnused(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, markCouponUnused, id)
	return err
}

const markCouponUsed = `-- name: MarkCouponUsed :exec
UPDATE coupons
SET is_used = true
WHERE id = $1
`

func (q *Queries) MarkCouponUsed(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, markCouponUsed, id)
	return err
}
