// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: coupons.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const countAllCoupons = `-- name: CountAllCoupons :one
SELECT COUNT(*) FROM coupons
`

func (q *Queries) CountAllCoupons(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countAllCoupons)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createCoupon = `-- name: CreateCoupon :one
INSERT INTO coupons (
    code, student_id, discount_percentage, expires_at
) VALUES (
    $1, $2, $3, $4
)
RETURNING id, code, student_id, discount_percentage, is_used, expires_at, created_at
`

type CreateCouponParams struct {
	Code               string             `json:"code"`
	StudentID          uuid.UUID          `json:"student_id"`
	DiscountPercentage int32              `json:"discount_percentage"`
	ExpiresAt          pgtype.Timestamptz `json:"expires_at"`
}

func (q *Queries) CreateCoupon(ctx context.Context, arg CreateCouponParams) (Coupon, error) {
	row := q.db.QueryRow(ctx, createCoupon,
		arg.Code,
		arg.StudentID,
		arg.DiscountPercentage,
		arg.ExpiresAt,
	)
	var i Coupon
	err := row.Scan(
		&i.ID,
		&i.Code,
		&i.StudentID,
		&i.DiscountPercentage,
		&i.IsUsed,
		&i.ExpiresAt,
		&i.CreatedAt,
	)
	return i, err
}

const getValidCoupon = `-- name: GetValidCoupon :one
SELECT id, code, student_id, discount_percentage, is_used, expires_at, created_at FROM coupons
WHERE code = $1
  AND student_id = $2
  AND is_used = false
  AND (expires_at IS NULL OR expires_at > NOW())
LIMIT 1
`

type GetValidCouponParams struct {
	Code      string    `json:"code"`
	StudentID uuid.UUID `json:"student_id"`
}

func (q *Queries) GetValidCoupon(ctx context.Context, arg GetValidCouponParams) (Coupon, error) {
	row := q.db.QueryRow(ctx, getValidCoupon, arg.Code, arg.StudentID)
	var i Coupon
	err := row.Scan(
		&i.ID,
		&i.Code,
		&i.StudentID,
		&i.DiscountPercentage,
		&i.IsUsed,
		&i.ExpiresAt,
		&i.CreatedAt,
	)
	return i, err
}

const listAllCoupons = `-- name: ListAllCoupons :many
SELECT
    c.id, c.code, c.student_id, c.discount_percentage, c.is_used, c.expires_at, c.created_at,
    u.name AS student_name, u.email AS student_email
FROM coupons c
JOIN users u ON u.id = c.student_id
ORDER BY c.created_at DESC
LIMIT $1 OFFSET $2
`

type ListAllCouponsParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

type ListAllCouponsRow struct {
	ID                 uuid.UUID          `json:"id"`
	Code               string             `json:"code"`
	StudentID          uuid.UUID          `json:"student_id"`
	DiscountPercentage int32              `json:"discount_percentage"`
	IsUsed             bool               `json:"is_used"`
	ExpiresAt          pgtype.Timestamptz `json:"expires_at"`
	CreatedAt          pgtype.Timestamptz `json:"created_at"`
	StudentName        string             `json:"student_name"`
	StudentEmail       string             `json:"student_email"`
}

func (q *Queries) ListAllCoupons(ctx context.Context, arg ListAllCouponsParams) ([]ListAllCouponsRow, error) {
	rows, err := q.db.Query(ctx, listAllCoupons, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListAllCouponsRow{}
	for rows.Next() {
		var i ListAllCouponsRow
		if err := rows.Scan(
			&i.ID,
			&i.Code,
			&i.StudentID,
			&i.DiscountPercentage,
			&i.IsUsed,
			&i.ExpiresAt,
			&i.CreatedAt,
			&i.StudentName,
			&i.StudentEmail,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markCouponUnused = `-- name: MarkCouponUnused :exec
UPDATE coupons
SET is_used = false
WHERE id = $1
`

func (q *Queries) MarkCouponUnused(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, markCouponUnused, id)
	return err
}

const markCouponUsed = `-- name: MarkCouponUsed :exec
UPDATE coupons
SET is_used = true
WHERE id = $1
`

func (q *Queries) MarkCouponUsed(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, markCouponUsed, id)
	return err
}
