// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: mentor_applications.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const approveMentorApplication = `-- name: ApproveMentorApplication :exec
UPDATE mentor_applications
SET status = 'approved', invite_code = $2, invite_code_expires_at = $3,
    reviewed_by = $4, updated_at = NOW()
WHERE id = $1
`

type ApproveMentorApplicationParams struct {
	ID                  uuid.UUID          `json:"id"`
	InviteCode          *string            `json:"invite_code"`
	InviteCodeExpiresAt pgtype.Timestamptz `json:"invite_code_expires_at"`
	ReviewedBy          pgtype.UUID        `json:"reviewed_by"`
}

func (q *Queries) ApproveMentorApplication(ctx context.Context, arg ApproveMentorApplicationParams) error {
	_, err := q.db.Exec(ctx, approveMentorApplication,
		arg.ID,
		arg.InviteCode,
		arg.InviteCodeExpiresAt,
		arg.ReviewedBy,
	)
	return err
}

const countMentorApplications = `-- name: CountMentorApplications :one
SELECT COUNT(*) FROM mentor_applications
`

func (q *Queries) CountMentorApplications(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countMentorApplications)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countMentorApplicationsByStatus = `-- name: CountMentorApplicationsByStatus :one
SELECT COUNT(*) FROM mentor_applications WHERE status = $1
`

func (q *Queries) CountMentorApplicationsByStatus(ctx context.Context, status string) (int64, error) {
	row := q.db.QueryRow(ctx, countMentorApplicationsByStatus, status)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createMentorApplication = `-- name: CreateMentorApplication :one
INSERT INTO mentor_applications (email, phone, about)
VALUES ($1, $2, $3)
RETURNING id, email, phone, about, status, invite_code, invite_code_expires_at, reviewed_by, created_at, updated_at
`

type CreateMentorApplicationParams struct {
	Email string `json:"email"`
	Phone string `json:"phone"`
	About string `json:"about"`
}

func (q *Queries) CreateMentorApplication(ctx context.Context, arg CreateMentorApplicationParams) (MentorApplication, error) {
	row := q.db.QueryRow(ctx, createMentorApplication, arg.Email, arg.Phone, arg.About)
	var i MentorApplication
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Phone,
		&i.About,
		&i.Status,
		&i.InviteCode,
		&i.InviteCodeExpiresAt,
		&i.ReviewedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getMentorApplicationByID = `-- name: GetMentorApplicationByID :one
SELECT id, email, phone, about, status, invite_code, invite_code_expires_at, reviewed_by, created_at, updated_at FROM mentor_applications WHERE id = $1
`

func (q *Queries) GetMentorApplicationByID(ctx context.Context, id uuid.UUID) (MentorApplication, error) {
	row := q.db.QueryRow(ctx, getMentorApplicationByID, id)
	var i MentorApplication
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Phone,
		&i.About,
		&i.Status,
		&i.InviteCode,
		&i.InviteCodeExpiresAt,
		&i.ReviewedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getMentorApplicationByInviteCode = `-- name: GetMentorApplicationByInviteCode :one
SELECT id, email, phone, about, status, invite_code, invite_code_expires_at, reviewed_by, created_at, updated_at FROM mentor_applications
WHERE invite_code = $1 AND status = 'approved' AND invite_code_expires_at > NOW()
`

func (q *Queries) GetMentorApplicationByInviteCode(ctx context.Context, inviteCode *string) (MentorApplication, error) {
	row := q.db.QueryRow(ctx, getMentorApplicationByInviteCode, inviteCode)
	var i MentorApplication
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Phone,
		&i.About,
		&i.Status,
		&i.InviteCode,
		&i.InviteCodeExpiresAt,
		&i.ReviewedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const invalidateInviteCode = `-- name: InvalidateInviteCode :exec
UPDATE mentor_applications
SET invite_code = NULL, invite_code_expires_at = NULL
WHERE id = $1
`

func (q *Queries) InvalidateInviteCode(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, invalidateInviteCode, id)
	return err
}

const listMentorApplications = `-- name: ListMentorApplications :many
SELECT id, email, phone, about, status, invite_code, invite_code_expires_at, reviewed_by, created_at, updated_at FROM mentor_applications
ORDER BY created_at DESC
LIMIT $1 OFFSET $2
`

type ListMentorApplicationsParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

func (q *Queries) ListMentorApplications(ctx context.Context, arg ListMentorApplicationsParams) ([]MentorApplication, error) {
	rows, err := q.db.Query(ctx, listMentorApplications, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []MentorApplication{}
	for rows.Next() {
		var i MentorApplication
		if err := rows.Scan(
			&i.ID,
			&i.Email,
			&i.Phone,
			&i.About,
			&i.Status,
			&i.InviteCode,
			&i.InviteCodeExpiresAt,
			&i.ReviewedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMentorApplicationsByStatus = `-- name: ListMentorApplicationsByStatus :many
SELECT id, email, phone, about, status, invite_code, invite_code_expires_at, reviewed_by, created_at, updated_at FROM mentor_applications
WHERE status = $1
ORDER BY created_at DESC
LIMIT $2 OFFSET $3
`

type ListMentorApplicationsByStatusParams struct {
	Status string `json:"status"`
	Limit  int32  `json:"limit"`
	Offset int32  `json:"offset"`
}

func (q *Queries) ListMentorApplicationsByStatus(ctx context.Context, arg ListMentorApplicationsByStatusParams) ([]MentorApplication, error) {
	rows, err := q.db.Query(ctx, listMentorApplicationsByStatus, arg.Status, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []MentorApplication{}
	for rows.Next() {
		var i MentorApplication
		if err := rows.Scan(
			&i.ID,
			&i.Email,
			&i.Phone,
			&i.About,
			&i.Status,
			&i.InviteCode,
			&i.InviteCodeExpiresAt,
			&i.ReviewedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const rejectMentorApplication = `-- name: RejectMentorApplication :exec
UPDATE mentor_applications
SET status = 'rejected', reviewed_by = $2, updated_at = NOW()
WHERE id = $1
`

type RejectMentorApplicationParams struct {
	ID         uuid.UUID   `json:"id"`
	ReviewedBy pgtype.UUID `json:"reviewed_by"`
}

func (q *Queries) RejectMentorApplication(ctx context.Context, arg RejectMentorApplicationParams) error {
	_, err := q.db.Exec(ctx, rejectMentorApplication, arg.ID, arg.ReviewedBy)
	return err
}
