// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: mentorship_plans.sql

package db

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const archivePlan = `-- name: ArchivePlan :exec
UPDATE mentorship_plans SET status = 'archived', updated_at = NOW() WHERE id = $1
`

func (q *Queries) ArchivePlan(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, archivePlan, id)
	return err
}

const countApprovedPlans = `-- name: CountApprovedPlans :one
SELECT COUNT(*) FROM mentorship_plans WHERE status = 'approved'
`

func (q *Queries) CountApprovedPlans(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countApprovedPlans)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countApprovedPlansByCategory = `-- name: CountApprovedPlansByCategory :one
SELECT COUNT(*) FROM mentorship_plans WHERE status = 'approved' AND category = $1
`

func (q *Queries) CountApprovedPlansByCategory(ctx context.Context, category string) (int64, error) {
	row := q.db.QueryRow(ctx, countApprovedPlansByCategory, category)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countPendingPlans = `-- name: CountPendingPlans :one
SELECT COUNT(*) FROM mentorship_plans WHERE status = 'pending_review'
`

func (q *Queries) CountPendingPlans(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countPendingPlans)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createAvailabilitySlot = `-- name: CreateAvailabilitySlot :one

INSERT INTO availability_slots (mentor_id, slot_type, day_of_week, specific_date, start_time, end_time)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, slot_type, day_of_week, specific_date, start_time, end_time, created_at, mentor_id
`

type CreateAvailabilitySlotParams struct {
	MentorID     uuid.UUID   `json:"mentor_id"`
	SlotType     string      `json:"slot_type"`
	DayOfWeek    *int32      `json:"day_of_week"`
	SpecificDate pgtype.Date `json:"specific_date"`
	StartTime    pgtype.Time `json:"start_time"`
	EndTime      pgtype.Time `json:"end_time"`
}

// ─────────────────────────────────────────────
// Availability Slots
// ─────────────────────────────────────────────
func (q *Queries) CreateAvailabilitySlot(ctx context.Context, arg CreateAvailabilitySlotParams) (AvailabilitySlot, error) {
	row := q.db.QueryRow(ctx, createAvailabilitySlot,
		arg.MentorID,
		arg.SlotType,
		arg.DayOfWeek,
		arg.SpecificDate,
		arg.StartTime,
		arg.EndTime,
	)
	var i AvailabilitySlot
	err := row.Scan(
		&i.ID,
		&i.SlotType,
		&i.DayOfWeek,
		&i.SpecificDate,
		&i.StartTime,
		&i.EndTime,
		&i.CreatedAt,
		&i.MentorID,
	)
	return i, err
}

const createMentorshipPlan = `-- name: CreateMentorshipPlan :one
INSERT INTO mentorship_plans (mentor_id, title, description, category, price_paise, duration_minutes, min_booking_notice_hours)
VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id, mentor_id, title, description, category, price_paise, duration_minutes, min_booking_notice_hours, status, rejection_reason, reviewed_by, created_at, updated_at
`

type CreateMentorshipPlanParams struct {
	MentorID              uuid.UUID `json:"mentor_id"`
	Title                 string    `json:"title"`
	Description           *string   `json:"description"`
	Category              string    `json:"category"`
	PricePaise            int32     `json:"price_paise"`
	DurationMinutes       int32     `json:"duration_minutes"`
	MinBookingNoticeHours int32     `json:"min_booking_notice_hours"`
}

func (q *Queries) CreateMentorshipPlan(ctx context.Context, arg CreateMentorshipPlanParams) (MentorshipPlan, error) {
	row := q.db.QueryRow(ctx, createMentorshipPlan,
		arg.MentorID,
		arg.Title,
		arg.Description,
		arg.Category,
		arg.PricePaise,
		arg.DurationMinutes,
		arg.MinBookingNoticeHours,
	)
	var i MentorshipPlan
	err := row.Scan(
		&i.ID,
		&i.MentorID,
		&i.Title,
		&i.Description,
		&i.Category,
		&i.PricePaise,
		&i.DurationMinutes,
		&i.MinBookingNoticeHours,
		&i.Status,
		&i.RejectionReason,
		&i.ReviewedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteAvailabilitySlotsByMentorID = `-- name: DeleteAvailabilitySlotsByMentorID :exec
DELETE FROM availability_slots WHERE mentor_id = $1
`

func (q *Queries) DeleteAvailabilitySlotsByMentorID(ctx context.Context, mentorID uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteAvailabilitySlotsByMentorID, mentorID)
	return err
}

const getAvailabilitySlotsByMentorID = `-- name: GetAvailabilitySlotsByMentorID :many
SELECT id, slot_type, day_of_week, specific_date, start_time, end_time, created_at, mentor_id FROM availability_slots
WHERE mentor_id = $1
ORDER BY COALESCE(day_of_week, 7), specific_date, start_time
`

func (q *Queries) GetAvailabilitySlotsByMentorID(ctx context.Context, mentorID uuid.UUID) ([]AvailabilitySlot, error) {
	rows, err := q.db.Query(ctx, getAvailabilitySlotsByMentorID, mentorID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AvailabilitySlot{}
	for rows.Next() {
		var i AvailabilitySlot
		if err := rows.Scan(
			&i.ID,
			&i.SlotType,
			&i.DayOfWeek,
			&i.SpecificDate,
			&i.StartTime,
			&i.EndTime,
			&i.CreatedAt,
			&i.MentorID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getMentorshipPlanByID = `-- name: GetMentorshipPlanByID :one
SELECT id, mentor_id, title, description, category, price_paise, duration_minutes, min_booking_notice_hours, status, rejection_reason, reviewed_by, created_at, updated_at FROM mentorship_plans WHERE id = $1
`

func (q *Queries) GetMentorshipPlanByID(ctx context.Context, id uuid.UUID) (MentorshipPlan, error) {
	row := q.db.QueryRow(ctx, getMentorshipPlanByID, id)
	var i MentorshipPlan
	err := row.Scan(
		&i.ID,
		&i.MentorID,
		&i.Title,
		&i.Description,
		&i.Category,
		&i.PricePaise,
		&i.DurationMinutes,
		&i.MinBookingNoticeHours,
		&i.Status,
		&i.RejectionReason,
		&i.ReviewedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listApprovedPlans = `-- name: ListApprovedPlans :many
SELECT id, mentor_id, title, description, category, price_paise, duration_minutes, min_booking_notice_hours, status, rejection_reason, reviewed_by, created_at, updated_at FROM mentorship_plans
WHERE status = 'approved'
ORDER BY created_at DESC
LIMIT $1 OFFSET $2
`

type ListApprovedPlansParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

func (q *Queries) ListApprovedPlans(ctx context.Context, arg ListApprovedPlansParams) ([]MentorshipPlan, error) {
	rows, err := q.db.Query(ctx, listApprovedPlans, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []MentorshipPlan{}
	for rows.Next() {
		var i MentorshipPlan
		if err := rows.Scan(
			&i.ID,
			&i.MentorID,
			&i.Title,
			&i.Description,
			&i.Category,
			&i.PricePaise,
			&i.DurationMinutes,
			&i.MinBookingNoticeHours,
			&i.Status,
			&i.RejectionReason,
			&i.ReviewedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listApprovedPlansByCategory = `-- name: ListApprovedPlansByCategory :many
SELECT id, mentor_id, title, description, category, price_paise, duration_minutes, min_booking_notice_hours, status, rejection_reason, reviewed_by, created_at, updated_at FROM mentorship_plans
WHERE status = 'approved' AND category = $1
ORDER BY created_at DESC
LIMIT $2 OFFSET $3
`

type ListApprovedPlansByCategoryParams struct {
	Category string `json:"category"`
	Limit    int32  `json:"limit"`
	Offset   int32  `json:"offset"`
}

func (q *Queries) ListApprovedPlansByCategory(ctx context.Context, arg ListApprovedPlansByCategoryParams) ([]MentorshipPlan, error) {
	rows, err := q.db.Query(ctx, listApprovedPlansByCategory, arg.Category, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []MentorshipPlan{}
	for rows.Next() {
		var i MentorshipPlan
		if err := rows.Scan(
			&i.ID,
			&i.MentorID,
			&i.Title,
			&i.Description,
			&i.Category,
			&i.PricePaise,
			&i.DurationMinutes,
			&i.MinBookingNoticeHours,
			&i.Status,
			&i.RejectionReason,
			&i.ReviewedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMentorPlans = `-- name: ListMentorPlans :many
SELECT id, mentor_id, title, description, category, price_paise, duration_minutes, min_booking_notice_hours, status, rejection_reason, reviewed_by, created_at, updated_at FROM mentorship_plans
WHERE mentor_id = $1
ORDER BY created_at DESC
`

func (q *Queries) ListMentorPlans(ctx context.Context, mentorID uuid.UUID) ([]MentorshipPlan, error) {
	rows, err := q.db.Query(ctx, listMentorPlans, mentorID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []MentorshipPlan{}
	for rows.Next() {
		var i MentorshipPlan
		if err := rows.Scan(
			&i.ID,
			&i.MentorID,
			&i.Title,
			&i.Description,
			&i.Category,
			&i.PricePaise,
			&i.DurationMinutes,
			&i.MinBookingNoticeHours,
			&i.Status,
			&i.RejectionReason,
			&i.ReviewedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPendingPlans = `-- name: ListPendingPlans :many
SELECT
    mp.id, mp.mentor_id, mp.title, mp.description, mp.category, mp.price_paise, mp.duration_minutes, mp.min_booking_notice_hours, mp.status, mp.rejection_reason, mp.reviewed_by, mp.created_at, mp.updated_at,
    u.name AS mentor_name, u.email AS mentor_email
FROM mentorship_plans mp
JOIN users u ON u.id = mp.mentor_id
WHERE mp.status = 'pending_review'
ORDER BY mp.created_at ASC
LIMIT $1 OFFSET $2
`

type ListPendingPlansParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

type ListPendingPlansRow struct {
	ID                    uuid.UUID   `json:"id"`
	MentorID              uuid.UUID   `json:"mentor_id"`
	Title                 string      `json:"title"`
	Description           *string     `json:"description"`
	Category              string      `json:"category"`
	PricePaise            int32       `json:"price_paise"`
	DurationMinutes       int32       `json:"duration_minutes"`
	MinBookingNoticeHours int32       `json:"min_booking_notice_hours"`
	Status                string      `json:"status"`
	RejectionReason       *string     `json:"rejection_reason"`
	ReviewedBy            pgtype.UUID `json:"reviewed_by"`
	CreatedAt             time.Time   `json:"created_at"`
	UpdatedAt             time.Time   `json:"updated_at"`
	MentorName            string      `json:"mentor_name"`
	MentorEmail           string      `json:"mentor_email"`
}

func (q *Queries) ListPendingPlans(ctx context.Context, arg ListPendingPlansParams) ([]ListPendingPlansRow, error) {
	rows, err := q.db.Query(ctx, listPendingPlans, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListPendingPlansRow{}
	for rows.Next() {
		var i ListPendingPlansRow
		if err := rows.Scan(
			&i.ID,
			&i.MentorID,
			&i.Title,
			&i.Description,
			&i.Category,
			&i.PricePaise,
			&i.DurationMinutes,
			&i.MinBookingNoticeHours,
			&i.Status,
			&i.RejectionReason,
			&i.ReviewedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.MentorName,
			&i.MentorEmail,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateMentorshipPlan = `-- name: UpdateMentorshipPlan :one
UPDATE mentorship_plans
SET title = $2, description = $3, category = $4, price_paise = $5,
    duration_minutes = $6, min_booking_notice_hours = $7,
    status = 'pending_review', rejection_reason = NULL, updated_at = NOW()
WHERE id = $1
RETURNING id, mentor_id, title, description, category, price_paise, duration_minutes, min_booking_notice_hours, status, rejection_reason, reviewed_by, created_at, updated_at
`

type UpdateMentorshipPlanParams struct {
	ID                    uuid.UUID `json:"id"`
	Title                 string    `json:"title"`
	Description           *string   `json:"description"`
	Category              string    `json:"category"`
	PricePaise            int32     `json:"price_paise"`
	DurationMinutes       int32     `json:"duration_minutes"`
	MinBookingNoticeHours int32     `json:"min_booking_notice_hours"`
}

func (q *Queries) UpdateMentorshipPlan(ctx context.Context, arg UpdateMentorshipPlanParams) (MentorshipPlan, error) {
	row := q.db.QueryRow(ctx, updateMentorshipPlan,
		arg.ID,
		arg.Title,
		arg.Description,
		arg.Category,
		arg.PricePaise,
		arg.DurationMinutes,
		arg.MinBookingNoticeHours,
	)
	var i MentorshipPlan
	err := row.Scan(
		&i.ID,
		&i.MentorID,
		&i.Title,
		&i.Description,
		&i.Category,
		&i.PricePaise,
		&i.DurationMinutes,
		&i.MinBookingNoticeHours,
		&i.Status,
		&i.RejectionReason,
		&i.ReviewedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updatePlanStatus = `-- name: UpdatePlanStatus :exec
UPDATE mentorship_plans
SET status = $2, rejection_reason = $3, reviewed_by = $4, updated_at = NOW()
WHERE id = $1
`

type UpdatePlanStatusParams struct {
	ID              uuid.UUID   `json:"id"`
	Status          string      `json:"status"`
	RejectionReason *string     `json:"rejection_reason"`
	ReviewedBy      pgtype.UUID `json:"reviewed_by"`
}

func (q *Queries) UpdatePlanStatus(ctx context.Context, arg UpdatePlanStatusParams) error {
	_, err := q.db.Exec(ctx, updatePlanStatus,
		arg.ID,
		arg.Status,
		arg.RejectionReason,
		arg.ReviewedBy,
	)
	return err
}
