// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: mentor_profiles.sql

package db

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const countMentorProfiles = `-- name: CountMentorProfiles :one
SELECT COUNT(*) FROM mentor_profiles
`

func (q *Queries) CountMentorProfiles(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countMentorProfiles)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createMentorProfile = `-- name: CreateMentorProfile :one
INSERT INTO mentor_profiles (user_id, phone, google_meet_link, bio)
VALUES ($1, $2, $3, $4)
RETURNING id, user_id, bio, achievements, documents, google_meet_link, phone, avg_rating, total_reviews, total_sessions, created_at, updated_at, min_booking_notice_hours, max_booking_advance_days
`

type CreateMentorProfileParams struct {
	UserID         uuid.UUID `json:"user_id"`
	Phone          *string   `json:"phone"`
	GoogleMeetLink *string   `json:"google_meet_link"`
	Bio            *string   `json:"bio"`
}

func (q *Queries) CreateMentorProfile(ctx context.Context, arg CreateMentorProfileParams) (MentorProfile, error) {
	row := q.db.QueryRow(ctx, createMentorProfile,
		arg.UserID,
		arg.Phone,
		arg.GoogleMeetLink,
		arg.Bio,
	)
	var i MentorProfile
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Bio,
		&i.Achievements,
		&i.Documents,
		&i.GoogleMeetLink,
		&i.Phone,
		&i.AvgRating,
		&i.TotalReviews,
		&i.TotalSessions,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.MinBookingNoticeHours,
		&i.MaxBookingAdvanceDays,
	)
	return i, err
}

const getMentorProfileByUserID = `-- name: GetMentorProfileByUserID :one
SELECT id, user_id, bio, achievements, documents, google_meet_link, phone, avg_rating, total_reviews, total_sessions, created_at, updated_at, min_booking_notice_hours, max_booking_advance_days FROM mentor_profiles WHERE user_id = $1
`

func (q *Queries) GetMentorProfileByUserID(ctx context.Context, userID uuid.UUID) (MentorProfile, error) {
	row := q.db.QueryRow(ctx, getMentorProfileByUserID, userID)
	var i MentorProfile
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Bio,
		&i.Achievements,
		&i.Documents,
		&i.GoogleMeetLink,
		&i.Phone,
		&i.AvgRating,
		&i.TotalReviews,
		&i.TotalSessions,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.MinBookingNoticeHours,
		&i.MaxBookingAdvanceDays,
	)
	return i, err
}

const getMentorPublicProfile = `-- name: GetMentorPublicProfile :one
SELECT
    mp.id, mp.user_id, mp.bio, mp.achievements, mp.documents,
    mp.google_meet_link, mp.phone, mp.avg_rating, mp.total_reviews,
    mp.total_sessions, mp.created_at, mp.updated_at,
    u.name AS user_name, u.email AS user_email, u.avatar_url AS user_avatar_url
FROM mentor_profiles mp
JOIN users u ON u.id = mp.user_id
WHERE mp.user_id = $1
`

type GetMentorPublicProfileRow struct {
	ID             uuid.UUID `json:"id"`
	UserID         uuid.UUID `json:"user_id"`
	Bio            *string   `json:"bio"`
	Achievements   []string  `json:"achievements"`
	Documents      []string  `json:"documents"`
	GoogleMeetLink *string   `json:"google_meet_link"`
	Phone          *string   `json:"phone"`
	AvgRating      float64   `json:"avg_rating"`
	TotalReviews   int32     `json:"total_reviews"`
	TotalSessions  int32     `json:"total_sessions"`
	CreatedAt      time.Time `json:"created_at"`
	UpdatedAt      time.Time `json:"updated_at"`
	UserName       string    `json:"user_name"`
	UserEmail      string    `json:"user_email"`
	UserAvatarUrl  *string   `json:"user_avatar_url"`
}

func (q *Queries) GetMentorPublicProfile(ctx context.Context, userID uuid.UUID) (GetMentorPublicProfileRow, error) {
	row := q.db.QueryRow(ctx, getMentorPublicProfile, userID)
	var i GetMentorPublicProfileRow
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Bio,
		&i.Achievements,
		&i.Documents,
		&i.GoogleMeetLink,
		&i.Phone,
		&i.AvgRating,
		&i.TotalReviews,
		&i.TotalSessions,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.UserName,
		&i.UserEmail,
		&i.UserAvatarUrl,
	)
	return i, err
}

const incrementMentorSessions = `-- name: IncrementMentorSessions :exec
UPDATE mentor_profiles
SET total_sessions = total_sessions + 1, updated_at = NOW()
WHERE user_id = $1
`

func (q *Queries) IncrementMentorSessions(ctx context.Context, userID uuid.UUID) error {
	_, err := q.db.Exec(ctx, incrementMentorSessions, userID)
	return err
}

const listMentorProfiles = `-- name: ListMentorProfiles :many
SELECT
    mp.id, mp.user_id, mp.bio, mp.achievements, mp.documents,
    mp.google_meet_link, mp.phone, mp.avg_rating, mp.total_reviews,
    mp.total_sessions, mp.created_at, mp.updated_at,
    u.name AS user_name, u.email AS user_email, u.avatar_url AS user_avatar_url
FROM mentor_profiles mp
JOIN users u ON u.id = mp.user_id
WHERE u.role = 'mentor'
ORDER BY mp.avg_rating DESC, mp.total_sessions DESC
LIMIT $1 OFFSET $2
`

type ListMentorProfilesParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

type ListMentorProfilesRow struct {
	ID             uuid.UUID `json:"id"`
	UserID         uuid.UUID `json:"user_id"`
	Bio            *string   `json:"bio"`
	Achievements   []string  `json:"achievements"`
	Documents      []string  `json:"documents"`
	GoogleMeetLink *string   `json:"google_meet_link"`
	Phone          *string   `json:"phone"`
	AvgRating      float64   `json:"avg_rating"`
	TotalReviews   int32     `json:"total_reviews"`
	TotalSessions  int32     `json:"total_sessions"`
	CreatedAt      time.Time `json:"created_at"`
	UpdatedAt      time.Time `json:"updated_at"`
	UserName       string    `json:"user_name"`
	UserEmail      string    `json:"user_email"`
	UserAvatarUrl  *string   `json:"user_avatar_url"`
}

func (q *Queries) ListMentorProfiles(ctx context.Context, arg ListMentorProfilesParams) ([]ListMentorProfilesRow, error) {
	rows, err := q.db.Query(ctx, listMentorProfiles, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListMentorProfilesRow{}
	for rows.Next() {
		var i ListMentorProfilesRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Bio,
			&i.Achievements,
			&i.Documents,
			&i.GoogleMeetLink,
			&i.Phone,
			&i.AvgRating,
			&i.TotalReviews,
			&i.TotalSessions,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.UserName,
			&i.UserEmail,
			&i.UserAvatarUrl,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateMentorAvailabilitySettings = `-- name: UpdateMentorAvailabilitySettings :one
UPDATE mentor_profiles
SET min_booking_notice_hours = $2, max_booking_advance_days = $3, updated_at = NOW()
WHERE user_id = $1
RETURNING id, user_id, bio, achievements, documents, google_meet_link, phone, avg_rating, total_reviews, total_sessions, created_at, updated_at, min_booking_notice_hours, max_booking_advance_days
`

type UpdateMentorAvailabilitySettingsParams struct {
	UserID                uuid.UUID `json:"user_id"`
	MinBookingNoticeHours int32     `json:"min_booking_notice_hours"`
	MaxBookingAdvanceDays int32     `json:"max_booking_advance_days"`
}

func (q *Queries) UpdateMentorAvailabilitySettings(ctx context.Context, arg UpdateMentorAvailabilitySettingsParams) (MentorProfile, error) {
	row := q.db.QueryRow(ctx, updateMentorAvailabilitySettings, arg.UserID, arg.MinBookingNoticeHours, arg.MaxBookingAdvanceDays)
	var i MentorProfile
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Bio,
		&i.Achievements,
		&i.Documents,
		&i.GoogleMeetLink,
		&i.Phone,
		&i.AvgRating,
		&i.TotalReviews,
		&i.TotalSessions,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.MinBookingNoticeHours,
		&i.MaxBookingAdvanceDays,
	)
	return i, err
}

const updateMentorProfile = `-- name: UpdateMentorProfile :one
UPDATE mentor_profiles
SET bio = $2, achievements = $3, documents = $4,
    google_meet_link = $5, phone = $6, updated_at = NOW()
WHERE user_id = $1
RETURNING id, user_id, bio, achievements, documents, google_meet_link, phone, avg_rating, total_reviews, total_sessions, created_at, updated_at, min_booking_notice_hours, max_booking_advance_days
`

type UpdateMentorProfileParams struct {
	UserID         uuid.UUID `json:"user_id"`
	Bio            *string   `json:"bio"`
	Achievements   []string  `json:"achievements"`
	Documents      []string  `json:"documents"`
	GoogleMeetLink *string   `json:"google_meet_link"`
	Phone          *string   `json:"phone"`
}

func (q *Queries) UpdateMentorProfile(ctx context.Context, arg UpdateMentorProfileParams) (MentorProfile, error) {
	row := q.db.QueryRow(ctx, updateMentorProfile,
		arg.UserID,
		arg.Bio,
		arg.Achievements,
		arg.Documents,
		arg.GoogleMeetLink,
		arg.Phone,
	)
	var i MentorProfile
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Bio,
		&i.Achievements,
		&i.Documents,
		&i.GoogleMeetLink,
		&i.Phone,
		&i.AvgRating,
		&i.TotalReviews,
		&i.TotalSessions,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.MinBookingNoticeHours,
		&i.MaxBookingAdvanceDays,
	)
	return i, err
}

const updateMentorRating = `-- name: UpdateMentorRating :exec
UPDATE mentor_profiles
SET avg_rating = $2, total_reviews = $3, updated_at = NOW()
WHERE user_id = $1
`

type UpdateMentorRatingParams struct {
	UserID       uuid.UUID `json:"user_id"`
	AvgRating    float64   `json:"avg_rating"`
	TotalReviews int32     `json:"total_reviews"`
}

func (q *Queries) UpdateMentorRating(ctx context.Context, arg UpdateMentorRatingParams) error {
	_, err := q.db.Exec(ctx, updateMentorRating, arg.UserID, arg.AvgRating, arg.TotalReviews)
	return err
}
