// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type User struct {
	ID              uuid.UUID          `json:"id"`
	Email           string             `json:"email"`
	Phone           pgtype.Text        `json:"phone"`
	PasswordHash    string             `json:"password_hash"`
	ProfileImageUrl pgtype.Text        `json:"profile_image_url"`
	FullName        string             `json:"full_name"`
	Role            string             `json:"role"`
	IsVerified      bool               `json:"is_verified"`
	CreatedAt       time.Time          `json:"created_at"`
	UpdatedAt       time.Time          `json:"updated_at"`
	LastLoginAt     pgtype.Timestamptz `json:"last_login_at"`
	DeletedAt       pgtype.Timestamptz `json:"deleted_at"`
}
