// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type AvailabilitySlot struct {
	ID           uuid.UUID   `json:"id"`
	PlanID       uuid.UUID   `json:"plan_id"`
	SlotType     string      `json:"slot_type"`
	DayOfWeek    *int32      `json:"day_of_week"`
	SpecificDate pgtype.Date `json:"specific_date"`
	StartTime    pgtype.Time `json:"start_time"`
	EndTime      pgtype.Time `json:"end_time"`
	CreatedAt    time.Time   `json:"created_at"`
	MentorID     pgtype.UUID `json:"mentor_id"`
}

type Booking struct {
	ID             uuid.UUID   `json:"id"`
	StudentID      uuid.UUID   `json:"student_id"`
	MentorID       uuid.UUID   `json:"mentor_id"`
	PlanID         uuid.UUID   `json:"plan_id"`
	SessionDate    pgtype.Date `json:"session_date"`
	StartTime      pgtype.Time `json:"start_time"`
	EndTime        pgtype.Time `json:"end_time"`
	GoogleMeetLink *string     `json:"google_meet_link"`
	Status         string      `json:"status"`
	CreatedAt      time.Time   `json:"created_at"`
	UpdatedAt      time.Time   `json:"updated_at"`
	CouponID       pgtype.UUID `json:"coupon_id"`
}

type Coupon struct {
	ID                 uuid.UUID          `json:"id"`
	Code               string             `json:"code"`
	StudentID          uuid.UUID          `json:"student_id"`
	DiscountPercentage int32              `json:"discount_percentage"`
	IsUsed             bool               `json:"is_used"`
	ExpiresAt          pgtype.Timestamptz `json:"expires_at"`
	CreatedAt          pgtype.Timestamptz `json:"created_at"`
}

type MentorApplication struct {
	ID                  uuid.UUID          `json:"id"`
	Email               string             `json:"email"`
	Phone               string             `json:"phone"`
	About               string             `json:"about"`
	Status              string             `json:"status"`
	InviteCode          *string            `json:"invite_code"`
	InviteCodeExpiresAt pgtype.Timestamptz `json:"invite_code_expires_at"`
	ReviewedBy          pgtype.UUID        `json:"reviewed_by"`
	CreatedAt           time.Time          `json:"created_at"`
	UpdatedAt           time.Time          `json:"updated_at"`
}

type MentorProfile struct {
	ID                    uuid.UUID `json:"id"`
	UserID                uuid.UUID `json:"user_id"`
	Bio                   *string   `json:"bio"`
	Achievements          []string  `json:"achievements"`
	Documents             []string  `json:"documents"`
	GoogleMeetLink        *string   `json:"google_meet_link"`
	Phone                 *string   `json:"phone"`
	AvgRating             float64   `json:"avg_rating"`
	TotalReviews          int32     `json:"total_reviews"`
	TotalSessions         int32     `json:"total_sessions"`
	CreatedAt             time.Time `json:"created_at"`
	UpdatedAt             time.Time `json:"updated_at"`
	MinBookingNoticeHours int32     `json:"min_booking_notice_hours"`
	MaxBookingAdvanceDays int32     `json:"max_booking_advance_days"`
}

type MentorshipPlan struct {
	ID              uuid.UUID   `json:"id"`
	MentorID        uuid.UUID   `json:"mentor_id"`
	Title           string      `json:"title"`
	Description     *string     `json:"description"`
	Category        string      `json:"category"`
	PricePaise      int32       `json:"price_paise"`
	DurationMinutes int32       `json:"duration_minutes"`
	Status          string      `json:"status"`
	RejectionReason *string     `json:"rejection_reason"`
	ReviewedBy      pgtype.UUID `json:"reviewed_by"`
	CreatedAt       time.Time   `json:"created_at"`
	UpdatedAt       time.Time   `json:"updated_at"`
}

type OtpCode struct {
	ID        uuid.UUID `json:"id"`
	Email     string    `json:"email"`
	CodeHash  string    `json:"code_hash"`
	Purpose   string    `json:"purpose"`
	Attempts  int32     `json:"attempts"`
	ExpiresAt time.Time `json:"expires_at"`
	Used      bool      `json:"used"`
	CreatedAt time.Time `json:"created_at"`
}

type Payment struct {
	ID                uuid.UUID `json:"id"`
	BookingID         uuid.UUID `json:"booking_id"`
	StudentID         uuid.UUID `json:"student_id"`
	AmountPaise       int32     `json:"amount_paise"`
	Currency          string    `json:"currency"`
	RazorpayOrderID   *string   `json:"razorpay_order_id"`
	RazorpayPaymentID *string   `json:"razorpay_payment_id"`
	RazorpaySignature *string   `json:"razorpay_signature"`
	Status            string    `json:"status"`
	CreatedAt         time.Time `json:"created_at"`
	UpdatedAt         time.Time `json:"updated_at"`
	OrderNumber       *string   `json:"order_number"`
}

type RefreshToken struct {
	ID        uuid.UUID `json:"id"`
	UserID    uuid.UUID `json:"user_id"`
	TokenHash string    `json:"token_hash"`
	ExpiresAt time.Time `json:"expires_at"`
	Revoked   bool      `json:"revoked"`
	CreatedAt time.Time `json:"created_at"`
}

type Review struct {
	ID        uuid.UUID `json:"id"`
	BookingID uuid.UUID `json:"booking_id"`
	StudentID uuid.UUID `json:"student_id"`
	MentorID  uuid.UUID `json:"mentor_id"`
	Rating    int32     `json:"rating"`
	Comment   *string   `json:"comment"`
	CreatedAt time.Time `json:"created_at"`
}

type User struct {
	ID            uuid.UUID `json:"id"`
	Email         string    `json:"email"`
	PasswordHash  string    `json:"password_hash"`
	Name          string    `json:"name"`
	Role          string    `json:"role"`
	EmailVerified bool      `json:"email_verified"`
	AvatarUrl     *string   `json:"avatar_url"`
	CreatedAt     time.Time `json:"created_at"`
	UpdatedAt     time.Time `json:"updated_at"`
}
