// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: otp_codes.sql

package db

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const countRecentOTPs = `-- name: CountRecentOTPs :one
SELECT COUNT(*) FROM otp_codes
WHERE email = $1 AND purpose = $2 AND created_at > NOW() - INTERVAL '1 hour'
`

type CountRecentOTPsParams struct {
	Email   string `json:"email"`
	Purpose string `json:"purpose"`
}

func (q *Queries) CountRecentOTPs(ctx context.Context, arg CountRecentOTPsParams) (int64, error) {
	row := q.db.QueryRow(ctx, countRecentOTPs, arg.Email, arg.Purpose)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createOTP = `-- name: CreateOTP :one
INSERT INTO otp_codes (email, code_hash, purpose, expires_at)
VALUES ($1, $2, $3, $4)
RETURNING id, email, code_hash, purpose, attempts, expires_at, used, created_at
`

type CreateOTPParams struct {
	Email     string    `json:"email"`
	CodeHash  string    `json:"code_hash"`
	Purpose   string    `json:"purpose"`
	ExpiresAt time.Time `json:"expires_at"`
}

func (q *Queries) CreateOTP(ctx context.Context, arg CreateOTPParams) (OtpCode, error) {
	row := q.db.QueryRow(ctx, createOTP,
		arg.Email,
		arg.CodeHash,
		arg.Purpose,
		arg.ExpiresAt,
	)
	var i OtpCode
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.CodeHash,
		&i.Purpose,
		&i.Attempts,
		&i.ExpiresAt,
		&i.Used,
		&i.CreatedAt,
	)
	return i, err
}

const deleteExpiredOTPs = `-- name: DeleteExpiredOTPs :exec
DELETE FROM otp_codes WHERE expires_at < NOW()
`

func (q *Queries) DeleteExpiredOTPs(ctx context.Context) error {
	_, err := q.db.Exec(ctx, deleteExpiredOTPs)
	return err
}

const getLatestOTP = `-- name: GetLatestOTP :one
SELECT id, email, code_hash, purpose, attempts, expires_at, used, created_at FROM otp_codes
WHERE email = $1 AND purpose = $2 AND used = FALSE AND expires_at > NOW()
ORDER BY created_at DESC
LIMIT 1
`

type GetLatestOTPParams struct {
	Email   string `json:"email"`
	Purpose string `json:"purpose"`
}

func (q *Queries) GetLatestOTP(ctx context.Context, arg GetLatestOTPParams) (OtpCode, error) {
	row := q.db.QueryRow(ctx, getLatestOTP, arg.Email, arg.Purpose)
	var i OtpCode
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.CodeHash,
		&i.Purpose,
		&i.Attempts,
		&i.ExpiresAt,
		&i.Used,
		&i.CreatedAt,
	)
	return i, err
}

const incrementOTPAttempts = `-- name: IncrementOTPAttempts :exec
UPDATE otp_codes SET attempts = attempts + 1 WHERE id = $1
`

func (q *Queries) IncrementOTPAttempts(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, incrementOTPAttempts, id)
	return err
}

const markOTPUsed = `-- name: MarkOTPUsed :exec
UPDATE otp_codes SET used = TRUE WHERE id = $1
`

func (q *Queries) MarkOTPUsed(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, markOTPUsed, id)
	return err
}
