// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: payments.sql

package db

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const countAllPayments = `-- name: CountAllPayments :one
SELECT COUNT(*) FROM payments
`

func (q *Queries) CountAllPayments(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countAllPayments)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createPayment = `-- name: CreatePayment :one
INSERT INTO payments (booking_id, student_id, amount_paise, razorpay_order_id)
VALUES ($1, $2, $3, $4)
RETURNING id, booking_id, student_id, amount_paise, currency, razorpay_order_id, razorpay_payment_id, razorpay_signature, status, created_at, updated_at, order_number
`

type CreatePaymentParams struct {
	BookingID       uuid.UUID `json:"booking_id"`
	StudentID       uuid.UUID `json:"student_id"`
	AmountPaise     int32     `json:"amount_paise"`
	RazorpayOrderID *string   `json:"razorpay_order_id"`
}

func (q *Queries) CreatePayment(ctx context.Context, arg CreatePaymentParams) (Payment, error) {
	row := q.db.QueryRow(ctx, createPayment,
		arg.BookingID,
		arg.StudentID,
		arg.AmountPaise,
		arg.RazorpayOrderID,
	)
	var i Payment
	err := row.Scan(
		&i.ID,
		&i.BookingID,
		&i.StudentID,
		&i.AmountPaise,
		&i.Currency,
		&i.RazorpayOrderID,
		&i.RazorpayPaymentID,
		&i.RazorpaySignature,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.OrderNumber,
	)
	return i, err
}

const getPaymentByBookingID = `-- name: GetPaymentByBookingID :one
SELECT id, booking_id, student_id, amount_paise, currency, razorpay_order_id, razorpay_payment_id, razorpay_signature, status, created_at, updated_at, order_number FROM payments WHERE booking_id = $1
`

func (q *Queries) GetPaymentByBookingID(ctx context.Context, bookingID uuid.UUID) (Payment, error) {
	row := q.db.QueryRow(ctx, getPaymentByBookingID, bookingID)
	var i Payment
	err := row.Scan(
		&i.ID,
		&i.BookingID,
		&i.StudentID,
		&i.AmountPaise,
		&i.Currency,
		&i.RazorpayOrderID,
		&i.RazorpayPaymentID,
		&i.RazorpaySignature,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.OrderNumber,
	)
	return i, err
}

const getPaymentByRazorpayOrderID = `-- name: GetPaymentByRazorpayOrderID :one
SELECT id, booking_id, student_id, amount_paise, currency, razorpay_order_id, razorpay_payment_id, razorpay_signature, status, created_at, updated_at, order_number FROM payments WHERE razorpay_order_id = $1
`

func (q *Queries) GetPaymentByRazorpayOrderID(ctx context.Context, razorpayOrderID *string) (Payment, error) {
	row := q.db.QueryRow(ctx, getPaymentByRazorpayOrderID, razorpayOrderID)
	var i Payment
	err := row.Scan(
		&i.ID,
		&i.BookingID,
		&i.StudentID,
		&i.AmountPaise,
		&i.Currency,
		&i.RazorpayOrderID,
		&i.RazorpayPaymentID,
		&i.RazorpaySignature,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.OrderNumber,
	)
	return i, err
}

const listAllPayments = `-- name: ListAllPayments :many
SELECT
    p.id, p.booking_id, p.student_id, p.amount_paise, p.currency, p.razorpay_order_id, p.razorpay_payment_id, p.razorpay_signature, p.status, p.created_at, p.updated_at, p.order_number,
    u.name AS student_name, u.email AS student_email
FROM payments p
JOIN users u ON u.id = p.student_id
ORDER BY p.created_at DESC
LIMIT $1 OFFSET $2
`

type ListAllPaymentsParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

type ListAllPaymentsRow struct {
	ID                uuid.UUID `json:"id"`
	BookingID         uuid.UUID `json:"booking_id"`
	StudentID         uuid.UUID `json:"student_id"`
	AmountPaise       int32     `json:"amount_paise"`
	Currency          string    `json:"currency"`
	RazorpayOrderID   *string   `json:"razorpay_order_id"`
	RazorpayPaymentID *string   `json:"razorpay_payment_id"`
	RazorpaySignature *string   `json:"razorpay_signature"`
	Status            string    `json:"status"`
	CreatedAt         time.Time `json:"created_at"`
	UpdatedAt         time.Time `json:"updated_at"`
	OrderNumber       *string   `json:"order_number"`
	StudentName       string    `json:"student_name"`
	StudentEmail      string    `json:"student_email"`
}

func (q *Queries) ListAllPayments(ctx context.Context, arg ListAllPaymentsParams) ([]ListAllPaymentsRow, error) {
	rows, err := q.db.Query(ctx, listAllPayments, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListAllPaymentsRow{}
	for rows.Next() {
		var i ListAllPaymentsRow
		if err := rows.Scan(
			&i.ID,
			&i.BookingID,
			&i.StudentID,
			&i.AmountPaise,
			&i.Currency,
			&i.RazorpayOrderID,
			&i.RazorpayPaymentID,
			&i.RazorpaySignature,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.OrderNumber,
			&i.StudentName,
			&i.StudentEmail,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const sumCapturedPayments = `-- name: SumCapturedPayments :one
SELECT COALESCE(SUM(amount_paise), 0)::bigint AS total FROM payments WHERE status = 'captured'
`

func (q *Queries) SumCapturedPayments(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, sumCapturedPayments)
	var total int64
	err := row.Scan(&total)
	return total, err
}

const updatePaymentCaptured = `-- name: UpdatePaymentCaptured :exec
UPDATE payments
SET razorpay_payment_id = $2, razorpay_signature = $3, status = 'captured', updated_at = NOW()
WHERE id = $1
`

type UpdatePaymentCapturedParams struct {
	ID                uuid.UUID `json:"id"`
	RazorpayPaymentID *string   `json:"razorpay_payment_id"`
	RazorpaySignature *string   `json:"razorpay_signature"`
}

func (q *Queries) UpdatePaymentCaptured(ctx context.Context, arg UpdatePaymentCapturedParams) error {
	_, err := q.db.Exec(ctx, updatePaymentCaptured, arg.ID, arg.RazorpayPaymentID, arg.RazorpaySignature)
	return err
}

const updatePaymentFailed = `-- name: UpdatePaymentFailed :exec
UPDATE payments SET status = 'failed', updated_at = NOW() WHERE id = $1
`

func (q *Queries) UpdatePaymentFailed(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, updatePaymentFailed, id)
	return err
}
