// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"context"

	"github.com/google/uuid"
)

type Querier interface {
	ApproveMentorApplication(ctx context.Context, arg ApproveMentorApplicationParams) error
	ArchivePlan(ctx context.Context, id uuid.UUID) error
	CheckSlotConflict(ctx context.Context, arg CheckSlotConflictParams) (int64, error)
	CountAllBookings(ctx context.Context) (int64, error)
	CountAllCoupons(ctx context.Context) (int64, error)
	CountAllPayments(ctx context.Context) (int64, error)
	CountApprovedPlans(ctx context.Context) (int64, error)
	CountApprovedPlansByCategory(ctx context.Context, category string) (int64, error)
	CountBookingsByStatus(ctx context.Context, status string) (int64, error)
	CountMentorApplications(ctx context.Context) (int64, error)
	CountMentorApplicationsByStatus(ctx context.Context, status string) (int64, error)
	CountMentorBookings(ctx context.Context, mentorID uuid.UUID) (int64, error)
	CountMentorProfiles(ctx context.Context) (int64, error)
	CountMentorReviews(ctx context.Context, mentorID uuid.UUID) (int64, error)
	CountPendingPlans(ctx context.Context) (int64, error)
	CountRecentOTPs(ctx context.Context, arg CountRecentOTPsParams) (int64, error)
	CountStudentBookings(ctx context.Context, studentID uuid.UUID) (int64, error)
	CountUsers(ctx context.Context) (int64, error)
	CountUsersByRole(ctx context.Context, role string) (int64, error)
	// ─────────────────────────────────────────────
	// Availability Slots
	// ─────────────────────────────────────────────
	CreateAvailabilitySlot(ctx context.Context, arg CreateAvailabilitySlotParams) (AvailabilitySlot, error)
	CreateBooking(ctx context.Context, arg CreateBookingParams) (Booking, error)
	CreateCoupon(ctx context.Context, arg CreateCouponParams) (Coupon, error)
	CreateMentorApplication(ctx context.Context, arg CreateMentorApplicationParams) (MentorApplication, error)
	CreateMentorProfile(ctx context.Context, arg CreateMentorProfileParams) (MentorProfile, error)
	CreateMentorshipPlan(ctx context.Context, arg CreateMentorshipPlanParams) (MentorshipPlan, error)
	CreateOTP(ctx context.Context, arg CreateOTPParams) (OtpCode, error)
	CreatePayment(ctx context.Context, arg CreatePaymentParams) (Payment, error)
	CreateRefreshToken(ctx context.Context, arg CreateRefreshTokenParams) (RefreshToken, error)
	CreateReview(ctx context.Context, arg CreateReviewParams) (Review, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	DeleteAvailabilitySlotsByPlanID(ctx context.Context, planID uuid.UUID) error
	DeleteExpiredOTPs(ctx context.Context) error
	DeleteExpiredRefreshTokens(ctx context.Context) error
	GetAvailabilitySlotsByPlanID(ctx context.Context, planID uuid.UUID) ([]AvailabilitySlot, error)
	GetBookingByID(ctx context.Context, id uuid.UUID) (Booking, error)
	GetLatestOTP(ctx context.Context, arg GetLatestOTPParams) (OtpCode, error)
	GetMentorApplicationByID(ctx context.Context, id uuid.UUID) (MentorApplication, error)
	GetMentorApplicationByInviteCode(ctx context.Context, inviteCode *string) (MentorApplication, error)
	GetMentorAverageRating(ctx context.Context, mentorID uuid.UUID) (GetMentorAverageRatingRow, error)
	GetMentorProfileByUserID(ctx context.Context, userID uuid.UUID) (MentorProfile, error)
	GetMentorPublicProfile(ctx context.Context, userID uuid.UUID) (GetMentorPublicProfileRow, error)
	GetMentorshipPlanByID(ctx context.Context, id uuid.UUID) (MentorshipPlan, error)
	GetPaymentByBookingID(ctx context.Context, bookingID uuid.UUID) (Payment, error)
	GetPaymentByRazorpayOrderID(ctx context.Context, razorpayOrderID *string) (Payment, error)
	GetRefreshTokenByHash(ctx context.Context, tokenHash string) (RefreshToken, error)
	GetReviewByBookingID(ctx context.Context, bookingID uuid.UUID) (Review, error)
	GetUserByEmail(ctx context.Context, email string) (User, error)
	GetUserByID(ctx context.Context, id uuid.UUID) (User, error)
	GetValidCoupon(ctx context.Context, arg GetValidCouponParams) (Coupon, error)
	IncrementMentorSessions(ctx context.Context, userID uuid.UUID) error
	IncrementOTPAttempts(ctx context.Context, id uuid.UUID) error
	InvalidateInviteCode(ctx context.Context, id uuid.UUID) error
	ListAllBookings(ctx context.Context, arg ListAllBookingsParams) ([]ListAllBookingsRow, error)
	ListAllCoupons(ctx context.Context, arg ListAllCouponsParams) ([]ListAllCouponsRow, error)
	ListAllPayments(ctx context.Context, arg ListAllPaymentsParams) ([]ListAllPaymentsRow, error)
	ListApprovedPlans(ctx context.Context, arg ListApprovedPlansParams) ([]MentorshipPlan, error)
	ListApprovedPlansByCategory(ctx context.Context, arg ListApprovedPlansByCategoryParams) ([]MentorshipPlan, error)
	ListMentorApplications(ctx context.Context, arg ListMentorApplicationsParams) ([]MentorApplication, error)
	ListMentorApplicationsByStatus(ctx context.Context, arg ListMentorApplicationsByStatusParams) ([]MentorApplication, error)
	ListMentorBookings(ctx context.Context, arg ListMentorBookingsParams) ([]ListMentorBookingsRow, error)
	ListMentorPlans(ctx context.Context, mentorID uuid.UUID) ([]MentorshipPlan, error)
	ListMentorProfiles(ctx context.Context, arg ListMentorProfilesParams) ([]ListMentorProfilesRow, error)
	ListMentorReviews(ctx context.Context, arg ListMentorReviewsParams) ([]ListMentorReviewsRow, error)
	ListPendingPlans(ctx context.Context, arg ListPendingPlansParams) ([]ListPendingPlansRow, error)
	ListStudentBookings(ctx context.Context, arg ListStudentBookingsParams) ([]ListStudentBookingsRow, error)
	ListUsers(ctx context.Context, arg ListUsersParams) ([]User, error)
	MarkCouponUnused(ctx context.Context, id uuid.UUID) error
	MarkCouponUsed(ctx context.Context, id uuid.UUID) error
	MarkOTPUsed(ctx context.Context, id uuid.UUID) error
	RejectMentorApplication(ctx context.Context, arg RejectMentorApplicationParams) error
	RevokeAllUserRefreshTokens(ctx context.Context, userID uuid.UUID) error
	RevokeRefreshToken(ctx context.Context, id uuid.UUID) error
	SumCapturedPayments(ctx context.Context) (int64, error)
	UpdateBookingStatus(ctx context.Context, arg UpdateBookingStatusParams) error
	UpdateEmailVerified(ctx context.Context, id uuid.UUID) error
	UpdateMentorProfile(ctx context.Context, arg UpdateMentorProfileParams) (MentorProfile, error)
	UpdateMentorRating(ctx context.Context, arg UpdateMentorRatingParams) error
	UpdateMentorshipPlan(ctx context.Context, arg UpdateMentorshipPlanParams) (MentorshipPlan, error)
	UpdatePassword(ctx context.Context, arg UpdatePasswordParams) error
	UpdatePaymentCaptured(ctx context.Context, arg UpdatePaymentCapturedParams) error
	UpdatePaymentFailed(ctx context.Context, id uuid.UUID) error
	UpdatePlanStatus(ctx context.Context, arg UpdatePlanStatusParams) error
	UpdateUserProfile(ctx context.Context, arg UpdateUserProfileParams) (User, error)
}

var _ Querier = (*Queries)(nil)
