// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: reviews.sql

package db

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const countMentorReviews = `-- name: CountMentorReviews :one
SELECT COUNT(*) FROM reviews WHERE mentor_id = $1
`

func (q *Queries) CountMentorReviews(ctx context.Context, mentorID uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countMentorReviews, mentorID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createReview = `-- name: CreateReview :one
INSERT INTO reviews (booking_id, student_id, mentor_id, rating, comment)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, booking_id, student_id, mentor_id, rating, comment, created_at
`

type CreateReviewParams struct {
	BookingID uuid.UUID `json:"booking_id"`
	StudentID uuid.UUID `json:"student_id"`
	MentorID  uuid.UUID `json:"mentor_id"`
	Rating    int32     `json:"rating"`
	Comment   *string   `json:"comment"`
}

func (q *Queries) CreateReview(ctx context.Context, arg CreateReviewParams) (Review, error) {
	row := q.db.QueryRow(ctx, createReview,
		arg.BookingID,
		arg.StudentID,
		arg.MentorID,
		arg.Rating,
		arg.Comment,
	)
	var i Review
	err := row.Scan(
		&i.ID,
		&i.BookingID,
		&i.StudentID,
		&i.MentorID,
		&i.Rating,
		&i.Comment,
		&i.CreatedAt,
	)
	return i, err
}

const getMentorAverageRating = `-- name: GetMentorAverageRating :one
SELECT
    COALESCE(AVG(rating), 0)::float8 AS avg_rating,
    COUNT(*)::bigint AS total_reviews
FROM reviews
WHERE mentor_id = $1
`

type GetMentorAverageRatingRow struct {
	AvgRating    float64 `json:"avg_rating"`
	TotalReviews int64   `json:"total_reviews"`
}

func (q *Queries) GetMentorAverageRating(ctx context.Context, mentorID uuid.UUID) (GetMentorAverageRatingRow, error) {
	row := q.db.QueryRow(ctx, getMentorAverageRating, mentorID)
	var i GetMentorAverageRatingRow
	err := row.Scan(&i.AvgRating, &i.TotalReviews)
	return i, err
}

const getReviewByBookingID = `-- name: GetReviewByBookingID :one
SELECT id, booking_id, student_id, mentor_id, rating, comment, created_at FROM reviews WHERE booking_id = $1
`

func (q *Queries) GetReviewByBookingID(ctx context.Context, bookingID uuid.UUID) (Review, error) {
	row := q.db.QueryRow(ctx, getReviewByBookingID, bookingID)
	var i Review
	err := row.Scan(
		&i.ID,
		&i.BookingID,
		&i.StudentID,
		&i.MentorID,
		&i.Rating,
		&i.Comment,
		&i.CreatedAt,
	)
	return i, err
}

const listMentorReviews = `-- name: ListMentorReviews :many
SELECT
    r.id, r.booking_id, r.student_id, r.mentor_id, r.rating, r.comment, r.created_at,
    u.name AS student_name
FROM reviews r
JOIN users u ON u.id = r.student_id
WHERE r.mentor_id = $1
ORDER BY r.created_at DESC
LIMIT $2 OFFSET $3
`

type ListMentorReviewsParams struct {
	MentorID uuid.UUID `json:"mentor_id"`
	Limit    int32     `json:"limit"`
	Offset   int32     `json:"offset"`
}

type ListMentorReviewsRow struct {
	ID          uuid.UUID `json:"id"`
	BookingID   uuid.UUID `json:"booking_id"`
	StudentID   uuid.UUID `json:"student_id"`
	MentorID    uuid.UUID `json:"mentor_id"`
	Rating      int32     `json:"rating"`
	Comment     *string   `json:"comment"`
	CreatedAt   time.Time `json:"created_at"`
	StudentName string    `json:"student_name"`
}

func (q *Queries) ListMentorReviews(ctx context.Context, arg ListMentorReviewsParams) ([]ListMentorReviewsRow, error) {
	rows, err := q.db.Query(ctx, listMentorReviews, arg.MentorID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListMentorReviewsRow{}
	for rows.Next() {
		var i ListMentorReviewsRow
		if err := rows.Scan(
			&i.ID,
			&i.BookingID,
			&i.StudentID,
			&i.MentorID,
			&i.Rating,
			&i.Comment,
			&i.CreatedAt,
			&i.StudentName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
